name: publish

on:
  push:
    branches:
      - main

jobs:

  make-map:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: False
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: >-
          pip install geopy==2.4.1 folium==0.19.5
      - name: Build map
        run: >-
          mkdir map; python make-map.py
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: map/

  deploy-map:
    needs:
      - make-map
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download map artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: map/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4